name: atomuq

channels:
  - conda-forge

dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - joblib
  - jupyterlab
  - ipykernel
  - pip:
      - tqdm